export const siteConfig = {
  name: "Shivam Shah",
  title: "Shivam Shah — Creative Developer & AI Enthusiast",
  description: "Computer Science student building impactful digital products with AI, Full-Stack, and UX.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.shivam-shah.com.np",
  ogImage: "/og.png",
  author: {
    name: "Shivam Shah",
    role: "Developer & AI Enthusiast",
    email: "shivamshah9811@gmail.com",
    github: "https://github.com/itsvoidstack",
    linkedin: "https://linkedin.com/in/shivam-shah-ab0a51411",
    handle: "@itsvoidstack",
  },
  keywords: [
    "Shivam Shah",
    "Shivam Shah portfolio",
    "Shivam Shah developer",
    "Shivam Shah software developer",
    "Shivam Shah computer science",
    "Shivam Shah projects",
    "Shivam Shah GitHub",
    "Shivam Shah web developer",
    "Shivam Shah AI developer",
    "itsvoidstack",
    "Full-Stack Developer",
    "AI Enthusiast",
    "TypeScript",
    "Next.js",
    "React",
    "FastAPI",
    "Python",
    "Tessera",
  ],
  googleVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || "-cl_ep0VSNWxd2P414BokPK4rhs9sSoKzVmNDR4MKkk",
  bingVerification: process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION || "",
};
